// auto-generated via copy.ts    
export type IconName = 'zoom-out' |
	'zoom-in' |
	'youtube' |
	'yin-yang' |
	'yelp' |
	'xbox' |
	'x' |
	'x-square' |
	'x-square-fill' |
	'x-octagon' |
	'x-octagon-fill' |
	'x-lg' |
	'x-diamond' |
	'x-diamond-fill' |
	'x-circle' |
	'x-circle-fill' |
	'wrench' |
	'wrench-adjustable' |
	'wrench-adjustable-circle' |
	'wrench-adjustable-circle-fill' |
	'wordpress' |
	'windows' |
	'window' |
	'window-x' |
	'window-stack' |
	'window-split' |
	'window-sidebar' |
	'window-plus' |
	'window-fullscreen' |
	'window-dock' |
	'window-desktop' |
	'window-dash' |
	'wind' |
	'wikipedia' |
	'wifi' |
	'wifi-off' |
	'wifi-2' |
	'wifi-1' |
	'whatsapp' |
	'wechat' |
	'webcam' |
	'webcam-fill' |
	'water' |
	'watch' |
	'wallet2' |
	'wallet' |
	'wallet-fill' |
	'vr' |
	'volume-up' |
	'volume-up-fill' |
	'volume-off' |
	'volume-off-fill' |
	'volume-mute' |
	'volume-mute-fill' |
	'volume-down' |
	'volume-down-fill' |
	'voicemail' |
	'virus2' |
	'virus' |
	'vinyl' |
	'vinyl-fill' |
	'vimeo' |
	'vignette' |
	'view-stacked' |
	'view-list' |
	'vector-pen' |
	'valentine2' |
	'valentine' |
	'usb' |
	'usb-symbol' |
	'usb-plug' |
	'usb-plug-fill' |
	'usb-mini' |
	'usb-mini-fill' |
	'usb-micro' |
	'usb-micro-fill' |
	'usb-fill' |
	'usb-drive' |
	'usb-drive-fill' |
	'usb-c' |
	'usb-c-fill' |
	'upload' |
	'upc' |
	'upc-scan' |
	'unlock2' |
	'unlock2-fill' |
	'unlock' |
	'unlock-fill' |
	'universal-access' |
	'universal-access-circle' |
	'unity' |
	'union' |
	'unindent' |
	'umbrella' |
	'umbrella-fill' |
	'ui-radios' |
	'ui-radios-grid' |
	'ui-checks' |
	'ui-checks-grid' |
	'ubuntu' |
	'typescript' |
	'type' |
	'type-underline' |
	'type-strikethrough' |
	'type-italic' |
	'type-h6' |
	'type-h5' |
	'type-h4' |
	'type-h3' |
	'type-h2' |
	'type-h1' |
	'type-bold' |
	'twitter' |
	'twitter-x' |
	'twitch' |
	'tv' |
	'tv-fill' |
	'tux' |
	'tsunami' |
	'truck' |
	'truck-front' |
	'truck-front-fill' |
	'truck-flatbed' |
	'tropical-storm' |
	'trophy' |
	'trophy-fill' |
	'triangle' |
	'triangle-half' |
	'triangle-fill' |
	'trello' |
	'tree' |
	'tree-fill' |
	'trash3' |
	'trash3-fill' |
	'trash2' |
	'trash2-fill' |
	'trash' |
	'trash-fill' |
	'transparency' |
	'translate' |
	'train-lightrail-front' |
	'train-lightrail-front-fill' |
	'train-front' |
	'train-front-fill' |
	'train-freight-front' |
	'train-freight-front-fill' |
	'tornado' |
	'tools' |
	'toggles2' |
	'toggles' |
	'toggle2-on' |
	'toggle2-off' |
	'toggle-on' |
	'toggle-off' |
	'tiktok' |
	'ticket' |
	'ticket-perforated' |
	'ticket-perforated-fill' |
	'ticket-fill' |
	'ticket-detailed' |
	'ticket-detailed-fill' |
	'thunderbolt' |
	'thunderbolt-fill' |
	'three-dots' |
	'three-dots-vertical' |
	'threads' |
	'threads-fill' |
	'thermometer' |
	'thermometer-sun' |
	'thermometer-snow' |
	'thermometer-low' |
	'thermometer-high' |
	'thermometer-half' |
	'textarea' |
	'textarea-t' |
	'textarea-resize' |
	'text-wrap' |
	'text-right' |
	'text-paragraph' |
	'text-left' |
	'text-indent-right' |
	'text-indent-left' |
	'text-center' |
	'terminal' |
	'terminal-x' |
	'terminal-split' |
	'terminal-plus' |
	'terminal-fill' |
	'terminal-dash' |
	'tencent-qq' |
	'telephone' |
	'telephone-x' |
	'telephone-x-fill' |
	'telephone-plus' |
	'telephone-plus-fill' |
	'telephone-outbound' |
	'telephone-outbound-fill' |
	'telephone-minus' |
	'telephone-minus-fill' |
	'telephone-inbound' |
	'telephone-inbound-fill' |
	'telephone-forward' |
	'telephone-forward-fill' |
	'telephone-fill' |
	'telegram' |
	'taxi-front' |
	'taxi-front-fill' |
	'tags' |
	'tags-fill' |
	'tag' |
	'tag-fill' |
	'tablet' |
	'tablet-landscape' |
	'tablet-landscape-fill' |
	'tablet-fill' |
	'table' |
	'symmetry-vertical' |
	'symmetry-horizontal' |
	'superscript' |
	'sunset' |
	'sunset-fill' |
	'sunrise' |
	'sunrise-fill' |
	'sunglasses' |
	'sun' |
	'sun-fill' |
	'suitcase2' |
	'suitcase2-fill' |
	'suitcase' |
	'suitcase-lg' |
	'suitcase-lg-fill' |
	'suitcase-fill' |
	'suit-spade' |
	'suit-spade-fill' |
	'suit-heart' |
	'suit-heart-fill' |
	'suit-diamond' |
	'suit-diamond-fill' |
	'suit-club' |
	'suit-club-fill' |
	'subtract' |
	'substack' |
	'subscript' |
	'stripe' |
	'strava' |
	'stopwatch' |
	'stopwatch-fill' |
	'stoplights' |
	'stoplights-fill' |
	'stop' |
	'stop-fill' |
	'stop-circle' |
	'stop-circle-fill' |
	'stop-btn' |
	'stop-btn-fill' |
	'sticky' |
	'sticky-fill' |
	'stickies' |
	'stickies-fill' |
	'steam' |
	'stars' |
	'star' |
	'star-half' |
	'star-fill' |
	'stack' |
	'stack-overflow' |
	'square' |
	'square-half' |
	'square-fill' |
	'spotify' |
	'spellcheck' |
	'speedometer2' |
	'speedometer' |
	'speaker' |
	'speaker-fill' |
	'sourceforge' |
	'soundwave' |
	'sort-up' |
	'sort-up-alt' |
	'sort-numeric-up' |
	'sort-numeric-up-alt' |
	'sort-numeric-down' |
	'sort-numeric-down-alt' |
	'sort-down' |
	'sort-down-alt' |
	'sort-alpha-up' |
	'sort-alpha-up-alt' |
	'sort-alpha-down' |
	'sort-alpha-down-alt' |
	'snow3' |
	'snow2' |
	'snow' |
	'snapchat' |
	'smartwatch' |
	'sliders2' |
	'sliders2-vertical' |
	'sliders' |
	'slash' |
	'slash-square' |
	'slash-square-fill' |
	'slash-lg' |
	'slash-circle' |
	'slash-circle-fill' |
	'slack' |
	'skype' |
	'skip-start' |
	'skip-start-fill' |
	'skip-start-circle' |
	'skip-start-circle-fill' |
	'skip-start-btn' |
	'skip-start-btn-fill' |
	'skip-forward' |
	'skip-forward-fill' |
	'skip-forward-circle' |
	'skip-forward-circle-fill' |
	'skip-forward-btn' |
	'skip-forward-btn-fill' |
	'skip-end' |
	'skip-end-fill' |
	'skip-end-circle' |
	'skip-end-circle-fill' |
	'skip-end-btn' |
	'skip-end-btn-fill' |
	'skip-backward' |
	'skip-backward-fill' |
	'skip-backward-circle' |
	'skip-backward-circle-fill' |
	'skip-backward-btn' |
	'skip-backward-btn-fill' |
	'sina-weibo' |
	'sim' |
	'sim-slash' |
	'sim-slash-fill' |
	'sim-fill' |
	'signpost' |
	'signpost-split' |
	'signpost-split-fill' |
	'signpost-fill' |
	'signpost-2' |
	'signpost-2-fill' |
	'signal' |
	'sign-yield' |
	'sign-yield-fill' |
	'sign-turn-slight-right' |
	'sign-turn-slight-right-fill' |
	'sign-turn-slight-left' |
	'sign-turn-slight-left-fill' |
	'sign-turn-right' |
	'sign-turn-right-fill' |
	'sign-turn-left' |
	'sign-turn-left-fill' |
	'sign-stop' |
	'sign-stop-lights' |
	'sign-stop-lights-fill' |
	'sign-stop-fill' |
	'sign-railroad' |
	'sign-railroad-fill' |
	'sign-no-right-turn' |
	'sign-no-right-turn-fill' |
	'sign-no-parking' |
	'sign-no-parking-fill' |
	'sign-no-left-turn' |
	'sign-no-left-turn-fill' |
	'sign-merge-right' |
	'sign-merge-right-fill' |
	'sign-merge-left' |
	'sign-merge-left-fill' |
	'sign-intersection' |
	'sign-intersection-y' |
	'sign-intersection-y-fill' |
	'sign-intersection-t' |
	'sign-intersection-t-fill' |
	'sign-intersection-side' |
	'sign-intersection-side-fill' |
	'sign-intersection-fill' |
	'sign-do-not-enter' |
	'sign-do-not-enter-fill' |
	'sign-dead-end' |
	'sign-dead-end-fill' |
	'shuffle' |
	'shop' |
	'shop-window' |
	'shift' |
	'shift-fill' |
	'shield' |
	'shield-x' |
	'shield-slash' |
	'shield-slash-fill' |
	'shield-shaded' |
	'shield-plus' |
	'shield-minus' |
	'shield-lock' |
	'shield-lock-fill' |
	'shield-fill' |
	'shield-fill-x' |
	'shield-fill-plus' |
	'shield-fill-minus' |
	'shield-fill-exclamation' |
	'shield-fill-check' |
	'shield-exclamation' |
	'shield-check' |
	'share' |
	'share-fill' |
	'shadows' |
	'server' |
	'send' |
	'send-x' |
	'send-x-fill' |
	'send-slash' |
	'send-slash-fill' |
	'send-plus' |
	'send-plus-fill' |
	'send-fill' |
	'send-exclamation' |
	'send-exclamation-fill' |
	'send-dash' |
	'send-dash-fill' |
	'send-check' |
	'send-check-fill' |
	'send-arrow-up' |
	'send-arrow-up-fill' |
	'send-arrow-down' |
	'send-arrow-down-fill' |
	'segmented-nav' |
	'search' |
	'search-heart' |
	'search-heart-fill' |
	'sd-card' |
	'sd-card-fill' |
	'screwdriver' |
	'scooter' |
	'scissors' |
	'save2' |
	'save2-fill' |
	'save' |
	'save-fill' |
	'safe2' |
	'safe2-fill' |
	'safe' |
	'safe-fill' |
	'rulers' |
	'rss' |
	'rss-fill' |
	'router' |
	'router-fill' |
	'rocket' |
	'rocket-takeoff' |
	'rocket-takeoff-fill' |
	'rocket-fill' |
	'robot' |
	'rewind' |
	'rewind-fill' |
	'rewind-circle' |
	'rewind-circle-fill' |
	'rewind-btn' |
	'rewind-btn-fill' |
	'reply' |
	'reply-fill' |
	'reply-all' |
	'reply-all-fill' |
	'repeat' |
	'repeat-1' |
	'regex' |
	'reddit' |
	'recycle' |
	'record2' |
	'record2-fill' |
	'record' |
	'record-fill' |
	'record-circle' |
	'record-circle-fill' |
	'record-btn' |
	'record-btn-fill' |
	'reception-4' |
	'reception-3' |
	'reception-2' |
	'reception-1' |
	'reception-0' |
	'receipt' |
	'receipt-cutoff' |
	'rainbow' |
	'radioactive' |
	'radar' |
	'r-square' |
	'r-square-fill' |
	'r-circle' |
	'r-circle-fill' |
	'quote' |
	'quora' |
	'question' |
	'question-square' |
	'question-square-fill' |
	'question-octagon' |
	'question-octagon-fill' |
	'question-lg' |
	'question-diamond' |
	'question-diamond-fill' |
	'question-circle' |
	'question-circle-fill' |
	'qr-code' |
	'qr-code-scan' |
	'puzzle' |
	'puzzle-fill' |
	'projector' |
	'projector-fill' |
	'printer' |
	'printer-fill' |
	'prescription2' |
	'prescription' |
	'power' |
	'postcard' |
	'postcard-heart' |
	'postcard-heart-fill' |
	'postcard-fill' |
	'postage' |
	'postage-heart' |
	'postage-heart-fill' |
	'postage-fill' |
	'plus' |
	'plus-square' |
	'plus-square-fill' |
	'plus-square-dotted' |
	'plus-slash-minus' |
	'plus-lg' |
	'plus-circle' |
	'plus-circle-fill' |
	'plus-circle-dotted' |
	'plugin' |
	'plug' |
	'plug-fill' |
	'playstation' |
	'play' |
	'play-fill' |
	'play-circle' |
	'play-circle-fill' |
	'play-btn' |
	'play-btn-fill' |
	'pip' |
	'pip-fill' |
	'pinterest' |
	'pin' |
	'pin-map' |
	'pin-map-fill' |
	'pin-fill' |
	'pin-angle' |
	'pin-angle-fill' |
	'piggy-bank' |
	'piggy-bank-fill' |
	'pie-chart' |
	'pie-chart-fill' |
	'phone' |
	'phone-vibrate' |
	'phone-vibrate-fill' |
	'phone-landscape' |
	'phone-landscape-fill' |
	'phone-flip' |
	'phone-fill' |
	'person' |
	'person-x' |
	'person-x-fill' |
	'person-workspace' |
	'person-wheelchair' |
	'person-walking' |
	'person-video3' |
	'person-video2' |
	'person-video' |
	'person-vcard' |
	'person-vcard-fill' |
	'person-up' |
	'person-standing' |
	'person-standing-dress' |
	'person-square' |
	'person-slash' |
	'person-rolodex' |
	'person-raised-hand' |
	'person-plus' |
	'person-plus-fill' |
	'person-lock' |
	'person-lines-fill' |
	'person-hearts' |
	'person-heart' |
	'person-gear' |
	'person-fill' |
	'person-fill-x' |
	'person-fill-up' |
	'person-fill-slash' |
	'person-fill-lock' |
	'person-fill-gear' |
	'person-fill-exclamation' |
	'person-fill-down' |
	'person-fill-dash' |
	'person-fill-check' |
	'person-fill-add' |
	'person-exclamation' |
	'person-down' |
	'person-dash' |
	'person-dash-fill' |
	'person-circle' |
	'person-check' |
	'person-check-fill' |
	'person-bounding-box' |
	'person-badge' |
	'person-badge-fill' |
	'person-arms-up' |
	'person-add' |
	'perplexity' |
	'percent' |
	'people' |
	'people-fill' |
	'pentagon' |
	'pentagon-half' |
	'pentagon-fill' |
	'pencil' |
	'pencil-square' |
	'pencil-fill' |
	'pen' |
	'pen-fill' |
	'peace' |
	'peace-fill' |
	'pci-card' |
	'pci-card-sound' |
	'pci-card-network' |
	'pc' |
	'pc-horizontal' |
	'pc-display' |
	'pc-display-horizontal' |
	'paypal' |
	'pause' |
	'pause-fill' |
	'pause-circle' |
	'pause-circle-fill' |
	'pause-btn' |
	'pause-btn-fill' |
	'patch-question' |
	'patch-question-fill' |
	'patch-plus' |
	'patch-plus-fill' |
	'patch-minus' |
	'patch-minus-fill' |
	'patch-exclamation' |
	'patch-exclamation-fill' |
	'patch-check' |
	'patch-check-fill' |
	'passport' |
	'passport-fill' |
	'pass' |
	'pass-fill' |
	'paragraph' |
	'paperclip' |
	'palette2' |
	'palette' |
	'palette-fill' |
	'paint-bucket' |
	'p-square' |
	'p-square-fill' |
	'p-circle' |
	'p-circle-fill' |
	'outlet' |
	'option' |
	'optical-audio' |
	'optical-audio-fill' |
	'opencollective' |
	'openai' |
	'octagon' |
	'octagon-half' |
	'octagon-fill' |
	'nvme' |
	'nvme-fill' |
	'nvidia' |
	'nut' |
	'nut-fill' |
	'noise-reduction' |
	'node-plus' |
	'node-plus-fill' |
	'node-minus' |
	'node-minus-fill' |
	'nintendo-switch' |
	'newspaper' |
	'music-player' |
	'music-player-fill' |
	'music-note' |
	'music-note-list' |
	'music-note-beamed' |
	'mouse3' |
	'mouse3-fill' |
	'mouse2' |
	'mouse2-fill' |
	'mouse' |
	'mouse-fill' |
	'motherboard' |
	'motherboard-fill' |
	'mortarboard' |
	'mortarboard-fill' |
	'moon' |
	'moon-stars' |
	'moon-stars-fill' |
	'moon-fill' |
	'moisture' |
	'modem' |
	'modem-fill' |
	'minecart' |
	'minecart-loaded' |
	'microsoft' |
	'microsoft-teams' |
	'mic' |
	'mic-mute' |
	'mic-mute-fill' |
	'mic-fill' |
	'meta' |
	'messenger' |
	'menu-up' |
	'menu-down' |
	'menu-button' |
	'menu-button-wide' |
	'menu-button-wide-fill' |
	'menu-button-fill' |
	'menu-app' |
	'menu-app-fill' |
	'memory' |
	'megaphone' |
	'megaphone-fill' |
	'medium' |
	'measuring-cup' |
	'measuring-cup-fill' |
	'mastodon' |
	'mask' |
	'marker-tip' |
	'markdown' |
	'markdown-fill' |
	'map' |
	'map-fill' |
	'mailbox2' |
	'mailbox2-flag' |
	'mailbox' |
	'mailbox-flag' |
	'magnet' |
	'magnet-fill' |
	'magic' |
	'lungs' |
	'lungs-fill' |
	'luggage' |
	'luggage-fill' |
	'lock' |
	'lock-fill' |
	'list' |
	'list-ul' |
	'list-task' |
	'list-stars' |
	'list-ol' |
	'list-nested' |
	'list-columns' |
	'list-columns-reverse' |
	'list-check' |
	'linkedin' |
	'link' |
	'link-45deg' |
	'line' |
	'lightning' |
	'lightning-fill' |
	'lightning-charge' |
	'lightning-charge-fill' |
	'lightbulb' |
	'lightbulb-off' |
	'lightbulb-off-fill' |
	'lightbulb-fill' |
	'life-preserver' |
	'leaf' |
	'leaf-fill' |
	'layout-wtf' |
	'layout-three-columns' |
	'layout-text-window' |
	'layout-text-window-reverse' |
	'layout-text-sidebar' |
	'layout-text-sidebar-reverse' |
	'layout-split' |
	'layout-sidebar' |
	'layout-sidebar-reverse' |
	'layout-sidebar-inset' |
	'layout-sidebar-inset-reverse' |
	'layers' |
	'layers-half' |
	'layers-fill' |
	'layer-forward' |
	'layer-backward' |
	'laptop' |
	'laptop-fill' |
	'lamp' |
	'lamp-fill' |
	'ladder' |
	'keyboard' |
	'keyboard-fill' |
	'key' |
	'key-fill' |
	'kanban' |
	'kanban-fill' |
	'justify' |
	'justify-right' |
	'justify-left' |
	'joystick' |
	'journals' |
	'journal' |
	'journal-x' |
	'journal-text' |
	'journal-richtext' |
	'journal-plus' |
	'journal-minus' |
	'journal-medical' |
	'journal-code' |
	'journal-check' |
	'journal-bookmark' |
	'journal-bookmark-fill' |
	'journal-arrow-up' |
	'journal-arrow-down' |
	'journal-album' |
	'javascript' |
	'intersect' |
	'instagram' |
	'input-cursor' |
	'input-cursor-text' |
	'info' |
	'info-square' |
	'info-square-fill' |
	'info-lg' |
	'info-circle' |
	'info-circle-fill' |
	'infinity' |
	'indent' |
	'incognito' |
	'inboxes' |
	'inboxes-fill' |
	'inbox' |
	'inbox-fill' |
	'images' |
	'image' |
	'image-fill' |
	'image-alt' |
	'hypnotize' |
	'hurricane' |
	'hr' |
	'houses' |
	'houses-fill' |
	'house' |
	'house-x' |
	'house-x-fill' |
	'house-up' |
	'house-up-fill' |
	'house-slash' |
	'house-slash-fill' |
	'house-lock' |
	'house-lock-fill' |
	'house-heart' |
	'house-heart-fill' |
	'house-gear' |
	'house-gear-fill' |
	'house-fill' |
	'house-exclamation' |
	'house-exclamation-fill' |
	'house-down' |
	'house-down-fill' |
	'house-door' |
	'house-door-fill' |
	'house-dash' |
	'house-dash-fill' |
	'house-check' |
	'house-check-fill' |
	'house-add' |
	'house-add-fill' |
	'hourglass' |
	'hourglass-top' |
	'hourglass-split' |
	'hourglass-bottom' |
	'hospital' |
	'hospital-fill' |
	'highlights' |
	'highlighter' |
	'hexagon' |
	'hexagon-half' |
	'hexagon-fill' |
	'heptagon' |
	'heptagon-half' |
	'heptagon-fill' |
	'hearts' |
	'heartbreak' |
	'heartbreak-fill' |
	'heart' |
	'heart-pulse' |
	'heart-pulse-fill' |
	'heart-half' |
	'heart-fill' |
	'heart-arrow' |
	'headset' |
	'headset-vr' |
	'headphones' |
	'hdmi' |
	'hdmi-fill' |
	'hdd' |
	'hdd-stack' |
	'hdd-stack-fill' |
	'hdd-rack' |
	'hdd-rack-fill' |
	'hdd-network' |
	'hdd-network-fill' |
	'hdd-fill' |
	'hash' |
	'handbag' |
	'handbag-fill' |
	'hand-thumbs-up' |
	'hand-thumbs-up-fill' |
	'hand-thumbs-down' |
	'hand-thumbs-down-fill' |
	'hand-index' |
	'hand-index-thumb' |
	'hand-index-thumb-fill' |
	'hand-index-fill' |
	'hammer' |
	'h-square' |
	'h-square-fill' |
	'h-circle' |
	'h-circle-fill' |
	'grip-vertical' |
	'grip-horizontal' |
	'grid' |
	'grid-fill' |
	'grid-3x3' |
	'grid-3x3-gap' |
	'grid-3x3-gap-fill' |
	'grid-3x2' |
	'grid-3x2-gap' |
	'grid-3x2-gap-fill' |
	'grid-1x2' |
	'grid-1x2-fill' |
	'graph-up' |
	'graph-up-arrow' |
	'graph-down' |
	'graph-down-arrow' |
	'gpu-card' |
	'google' |
	'google-play' |
	'globe2' |
	'globe' |
	'globe-europe-africa' |
	'globe-europe-africa-fill' |
	'globe-central-south-asia' |
	'globe-central-south-asia-fill' |
	'globe-asia-australia' |
	'globe-asia-australia-fill' |
	'globe-americas' |
	'globe-americas-fill' |
	'gitlab' |
	'github' |
	'git' |
	'gift' |
	'gift-fill' |
	'geo' |
	'geo-fill' |
	'geo-alt' |
	'geo-alt-fill' |
	'gender-trans' |
	'gender-neuter' |
	'gender-male' |
	'gender-female' |
	'gender-ambiguous' |
	'gem' |
	'gear' |
	'gear-wide' |
	'gear-wide-connected' |
	'gear-fill' |
	'funnel' |
	'funnel-fill' |
	'fullscreen' |
	'fullscreen-exit' |
	'fuel-pump' |
	'fuel-pump-fill' |
	'fuel-pump-diesel' |
	'fuel-pump-diesel-fill' |
	'front' |
	'forward' |
	'forward-fill' |
	'fork-knife' |
	'fonts' |
	'folder2' |
	'folder2-open' |
	'folder' |
	'folder-x' |
	'folder-symlink' |
	'folder-symlink-fill' |
	'folder-plus' |
	'folder-minus' |
	'folder-fill' |
	'folder-check' |
	'flower3' |
	'flower2' |
	'flower1' |
	'floppy2' |
	'floppy2-fill' |
	'floppy' |
	'floppy-fill' |
	'flask' |
	'flask-florence' |
	'flask-florence-fill' |
	'flask-fill' |
	'flag' |
	'flag-fill' |
	'fire' |
	'fingerprint' |
	'filter' |
	'filter-square' |
	'filter-square-fill' |
	'filter-right' |
	'filter-left' |
	'filter-circle' |
	'filter-circle-fill' |
	'film' |
	'filetype-yml' |
	'filetype-xml' |
	'filetype-xlsx' |
	'filetype-xls' |
	'filetype-woff' |
	'filetype-wav' |
	'filetype-txt' |
	'filetype-ttf' |
	'filetype-tsx' |
	'filetype-tiff' |
	'filetype-svg' |
	'filetype-sql' |
	'filetype-sh' |
	'filetype-scss' |
	'filetype-sass' |
	'filetype-rb' |
	'filetype-raw' |
	'filetype-py' |
	'filetype-psd' |
	'filetype-pptx' |
	'filetype-ppt' |
	'filetype-png' |
	'filetype-php' |
	'filetype-pdf' |
	'filetype-otf' |
	'filetype-mp4' |
	'filetype-mp3' |
	'filetype-mov' |
	'filetype-mdx' |
	'filetype-md' |
	'filetype-m4p' |
	'filetype-key' |
	'filetype-jsx' |
	'filetype-json' |
	'filetype-js' |
	'filetype-jpg' |
	'filetype-java' |
	'filetype-html' |
	'filetype-heic' |
	'filetype-gif' |
	'filetype-exe' |
	'filetype-docx' |
	'filetype-doc' |
	'filetype-csv' |
	'filetype-css' |
	'filetype-cs' |
	'filetype-bmp' |
	'filetype-ai' |
	'filetype-aac' |
	'files' |
	'files-alt' |
	'file' |
	'file-zip' |
	'file-zip-fill' |
	'file-x' |
	'file-x-fill' |
	'file-word' |
	'file-word-fill' |
	'file-text' |
	'file-text-fill' |
	'file-spreadsheet' |
	'file-spreadsheet-fill' |
	'file-slides' |
	'file-slides-fill' |
	'file-ruled' |
	'file-ruled-fill' |
	'file-richtext' |
	'file-richtext-fill' |
	'file-ppt' |
	'file-ppt-fill' |
	'file-post' |
	'file-post-fill' |
	'file-plus' |
	'file-plus-fill' |
	'file-play' |
	'file-play-fill' |
	'file-person' |
	'file-person-fill' |
	'file-pdf' |
	'file-pdf-fill' |
	'file-music' |
	'file-music-fill' |
	'file-minus' |
	'file-minus-fill' |
	'file-medical' |
	'file-medical-fill' |
	'file-lock2' |
	'file-lock2-fill' |
	'file-lock' |
	'file-lock-fill' |
	'file-image' |
	'file-image-fill' |
	'file-font' |
	'file-font-fill' |
	'file-fill' |
	'file-excel' |
	'file-excel-fill' |
	'file-easel' |
	'file-easel-fill' |
	'file-earmark' |
	'file-earmark-zip' |
	'file-earmark-zip-fill' |
	'file-earmark-x' |
	'file-earmark-x-fill' |
	'file-earmark-word' |
	'file-earmark-word-fill' |
	'file-earmark-text' |
	'file-earmark-text-fill' |
	'file-earmark-spreadsheet' |
	'file-earmark-spreadsheet-fill' |
	'file-earmark-slides' |
	'file-earmark-slides-fill' |
	'file-earmark-ruled' |
	'file-earmark-ruled-fill' |
	'file-earmark-richtext' |
	'file-earmark-richtext-fill' |
	'file-earmark-ppt' |
	'file-earmark-ppt-fill' |
	'file-earmark-post' |
	'file-earmark-post-fill' |
	'file-earmark-plus' |
	'file-earmark-plus-fill' |
	'file-earmark-play' |
	'file-earmark-play-fill' |
	'file-earmark-person' |
	'file-earmark-person-fill' |
	'file-earmark-pdf' |
	'file-earmark-pdf-fill' |
	'file-earmark-music' |
	'file-earmark-music-fill' |
	'file-earmark-minus' |
	'file-earmark-minus-fill' |
	'file-earmark-medical' |
	'file-earmark-medical-fill' |
	'file-earmark-lock2' |
	'file-earmark-lock2-fill' |
	'file-earmark-lock' |
	'file-earmark-lock-fill' |
	'file-earmark-image' |
	'file-earmark-image-fill' |
	'file-earmark-font' |
	'file-earmark-font-fill' |
	'file-earmark-fill' |
	'file-earmark-excel' |
	'file-earmark-excel-fill' |
	'file-earmark-easel' |
	'file-earmark-easel-fill' |
	'file-earmark-diff' |
	'file-earmark-diff-fill' |
	'file-earmark-code' |
	'file-earmark-code-fill' |
	'file-earmark-check' |
	'file-earmark-check-fill' |
	'file-earmark-break' |
	'file-earmark-break-fill' |
	'file-earmark-binary' |
	'file-earmark-binary-fill' |
	'file-earmark-bar-graph' |
	'file-earmark-bar-graph-fill' |
	'file-earmark-arrow-up' |
	'file-earmark-arrow-up-fill' |
	'file-earmark-arrow-down' |
	'file-earmark-arrow-down-fill' |
	'file-diff' |
	'file-diff-fill' |
	'file-code' |
	'file-code-fill' |
	'file-check' |
	'file-check-fill' |
	'file-break' |
	'file-break-fill' |
	'file-binary' |
	'file-binary-fill' |
	'file-bar-graph' |
	'file-bar-graph-fill' |
	'file-arrow-up' |
	'file-arrow-up-fill' |
	'file-arrow-down' |
	'file-arrow-down-fill' |
	'feather2' |
	'feather' |
	'fast-forward' |
	'fast-forward-fill' |
	'fast-forward-circle' |
	'fast-forward-circle-fill' |
	'fast-forward-btn' |
	'fast-forward-btn-fill' |
	'fan' |
	'facebook' |
	'eyeglasses' |
	'eyedropper' |
	'eye' |
	'eye-slash' |
	'eye-slash-fill' |
	'eye-fill' |
	'exposure' |
	'explicit' |
	'explicit-fill' |
	'exclude' |
	'exclamation' |
	'exclamation-triangle' |
	'exclamation-triangle-fill' |
	'exclamation-square' |
	'exclamation-square-fill' |
	'exclamation-octagon' |
	'exclamation-octagon-fill' |
	'exclamation-lg' |
	'exclamation-diamond' |
	'exclamation-diamond-fill' |
	'exclamation-circle' |
	'exclamation-circle-fill' |
	'ev-station' |
	'ev-station-fill' |
	'ev-front' |
	'ev-front-fill' |
	'ethernet' |
	'escape' |
	'eraser' |
	'eraser-fill' |
	'envelope' |
	'envelope-x' |
	'envelope-x-fill' |
	'envelope-slash' |
	'envelope-slash-fill' |
	'envelope-plus' |
	'envelope-plus-fill' |
	'envelope-paper' |
	'envelope-paper-heart' |
	'envelope-paper-heart-fill' |
	'envelope-paper-fill' |
	'envelope-open' |
	'envelope-open-heart' |
	'envelope-open-heart-fill' |
	'envelope-open-fill' |
	'envelope-heart' |
	'envelope-heart-fill' |
	'envelope-fill' |
	'envelope-exclamation' |
	'envelope-exclamation-fill' |
	'envelope-dash' |
	'envelope-dash-fill' |
	'envelope-check' |
	'envelope-check-fill' |
	'envelope-at' |
	'envelope-at-fill' |
	'envelope-arrow-up' |
	'envelope-arrow-up-fill' |
	'envelope-arrow-down' |
	'envelope-arrow-down-fill' |
	'emoji-wink' |
	'emoji-wink-fill' |
	'emoji-tear' |
	'emoji-tear-fill' |
	'emoji-surprise' |
	'emoji-surprise-fill' |
	'emoji-sunglasses' |
	'emoji-sunglasses-fill' |
	'emoji-smile' |
	'emoji-smile-upside-down' |
	'emoji-smile-upside-down-fill' |
	'emoji-smile-fill' |
	'emoji-neutral' |
	'emoji-neutral-fill' |
	'emoji-laughing' |
	'emoji-laughing-fill' |
	'emoji-kiss' |
	'emoji-kiss-fill' |
	'emoji-heart-eyes' |
	'emoji-heart-eyes-fill' |
	'emoji-grin' |
	'emoji-grin-fill' |
	'emoji-grimace' |
	'emoji-grimace-fill' |
	'emoji-frown' |
	'emoji-frown-fill' |
	'emoji-expressionless' |
	'emoji-expressionless-fill' |
	'emoji-dizzy' |
	'emoji-dizzy-fill' |
	'emoji-astonished' |
	'emoji-astonished-fill' |
	'emoji-angry' |
	'emoji-angry-fill' |
	'eject' |
	'eject-fill' |
	'egg' |
	'egg-fried' |
	'egg-fill' |
	'easel3' |
	'easel3-fill' |
	'easel2' |
	'easel2-fill' |
	'easel' |
	'easel-fill' |
	'earbuds' |
	'ear' |
	'ear-fill' |
	'duffle' |
	'duffle-fill' |
	'droplet' |
	'droplet-half' |
	'droplet-fill' |
	'dropbox' |
	'dribbble' |
	'dpad' |
	'dpad-fill' |
	'download' |
	'dot' |
	'door-open' |
	'door-open-fill' |
	'door-closed' |
	'door-closed-fill' |
	'distribute-vertical' |
	'distribute-horizontal' |
	'displayport' |
	'displayport-fill' |
	'display' |
	'display-fill' |
	'discord' |
	'disc' |
	'disc-fill' |
	'dice-6' |
	'dice-6-fill' |
	'dice-5' |
	'dice-5-fill' |
	'dice-4' |
	'dice-4-fill' |
	'dice-3' |
	'dice-3-fill' |
	'dice-2' |
	'dice-2-fill' |
	'dice-1' |
	'dice-1-fill' |
	'diamond' |
	'diamond-half' |
	'diamond-fill' |
	'diagram-3' |
	'diagram-3-fill' |
	'diagram-2' |
	'diagram-2-fill' |
	'device-ssd' |
	'device-ssd-fill' |
	'device-hdd' |
	'device-hdd-fill' |
	'database' |
	'database-x' |
	'database-up' |
	'database-slash' |
	'database-lock' |
	'database-gear' |
	'database-fill' |
	'database-fill-x' |
	'database-fill-up' |
	'database-fill-slash' |
	'database-fill-lock' |
	'database-fill-gear' |
	'database-fill-exclamation' |
	'database-fill-down' |
	'database-fill-dash' |
	'database-fill-check' |
	'database-fill-add' |
	'database-exclamation' |
	'database-down' |
	'database-dash' |
	'database-check' |
	'database-add' |
	'dash' |
	'dash-square' |
	'dash-square-fill' |
	'dash-square-dotted' |
	'dash-lg' |
	'dash-circle' |
	'dash-circle-fill' |
	'dash-circle-dotted' |
	'cursor' |
	'cursor-text' |
	'cursor-fill' |
	'currency-yen' |
	'currency-rupee' |
	'currency-pound' |
	'currency-exchange' |
	'currency-euro' |
	'currency-dollar' |
	'currency-bitcoin' |
	'cup' |
	'cup-straw' |
	'cup-hot' |
	'cup-hot-fill' |
	'cup-fill' |
	'css' |
	'crosshair2' |
	'crosshair' |
	'crop' |
	'credit-card' |
	'credit-card-fill' |
	'credit-card-2-front' |
	'credit-card-2-front-fill' |
	'credit-card-2-back' |
	'credit-card-2-back-fill' |
	'cpu' |
	'cpu-fill' |
	'copy' |
	'cookie' |
	'controller' |
	'cone' |
	'cone-striped' |
	'compass' |
	'compass-fill' |
	'command' |
	'columns' |
	'columns-gap' |
	'collection' |
	'collection-play' |
	'collection-play-fill' |
	'collection-fill' |
	'coin' |
	'code' |
	'code-square' |
	'code-slash' |
	'cloudy' |
	'cloudy-fill' |
	'clouds' |
	'clouds-fill' |
	'cloud' |
	'cloud-upload' |
	'cloud-upload-fill' |
	'cloud-sun' |
	'cloud-sun-fill' |
	'cloud-snow' |
	'cloud-snow-fill' |
	'cloud-sleet' |
	'cloud-sleet-fill' |
	'cloud-slash' |
	'cloud-slash-fill' |
	'cloud-rain' |
	'cloud-rain-heavy' |
	'cloud-rain-heavy-fill' |
	'cloud-rain-fill' |
	'cloud-plus' |
	'cloud-plus-fill' |
	'cloud-moon' |
	'cloud-moon-fill' |
	'cloud-minus' |
	'cloud-minus-fill' |
	'cloud-lightning' |
	'cloud-lightning-rain' |
	'cloud-lightning-rain-fill' |
	'cloud-lightning-fill' |
	'cloud-haze2' |
	'cloud-haze2-fill' |
	'cloud-haze' |
	'cloud-haze-fill' |
	'cloud-hail' |
	'cloud-hail-fill' |
	'cloud-fog2' |
	'cloud-fog2-fill' |
	'cloud-fog' |
	'cloud-fog-fill' |
	'cloud-fill' |
	'cloud-drizzle' |
	'cloud-drizzle-fill' |
	'cloud-download' |
	'cloud-download-fill' |
	'cloud-check' |
	'cloud-check-fill' |
	'cloud-arrow-up' |
	'cloud-arrow-up-fill' |
	'cloud-arrow-down' |
	'cloud-arrow-down-fill' |
	'clock' |
	'clock-history' |
	'clock-fill' |
	'clipboard2' |
	'clipboard2-x' |
	'clipboard2-x-fill' |
	'clipboard2-pulse' |
	'clipboard2-pulse-fill' |
	'clipboard2-plus' |
	'clipboard2-plus-fill' |
	'clipboard2-minus' |
	'clipboard2-minus-fill' |
	'clipboard2-heart' |
	'clipboard2-heart-fill' |
	'clipboard2-fill' |
	'clipboard2-data' |
	'clipboard2-data-fill' |
	'clipboard2-check' |
	'clipboard2-check-fill' |
	'clipboard' |
	'clipboard-x' |
	'clipboard-x-fill' |
	'clipboard-pulse' |
	'clipboard-plus' |
	'clipboard-plus-fill' |
	'clipboard-minus' |
	'clipboard-minus-fill' |
	'clipboard-heart' |
	'clipboard-heart-fill' |
	'clipboard-fill' |
	'clipboard-data' |
	'clipboard-data-fill' |
	'clipboard-check' |
	'clipboard-check-fill' |
	'claude' |
	'circle' |
	'circle-square' |
	'circle-half' |
	'circle-fill' |
	'chevron-up' |
	'chevron-right' |
	'chevron-left' |
	'chevron-expand' |
	'chevron-down' |
	'chevron-double-up' |
	'chevron-double-right' |
	'chevron-double-left' |
	'chevron-double-down' |
	'chevron-contract' |
	'chevron-compact-up' |
	'chevron-compact-right' |
	'chevron-compact-left' |
	'chevron-compact-down' |
	'chevron-bar-up' |
	'chevron-bar-right' |
	'chevron-bar-left' |
	'chevron-bar-expand' |
	'chevron-bar-down' |
	'chevron-bar-contract' |
	'check2' |
	'check2-square' |
	'check2-circle' |
	'check2-all' |
	'check' |
	'check-square' |
	'check-square-fill' |
	'check-lg' |
	'check-circle' |
	'check-circle-fill' |
	'check-all' |
	'chat' |
	'chat-text' |
	'chat-text-fill' |
	'chat-square' |
	'chat-square-text' |
	'chat-square-text-fill' |
	'chat-square-quote' |
	'chat-square-quote-fill' |
	'chat-square-heart' |
	'chat-square-heart-fill' |
	'chat-square-fill' |
	'chat-square-dots' |
	'chat-square-dots-fill' |
	'chat-right' |
	'chat-right-text' |
	'chat-right-text-fill' |
	'chat-right-quote' |
	'chat-right-quote-fill' |
	'chat-right-heart' |
	'chat-right-heart-fill' |
	'chat-right-fill' |
	'chat-right-dots' |
	'chat-right-dots-fill' |
	'chat-quote' |
	'chat-quote-fill' |
	'chat-left' |
	'chat-left-text' |
	'chat-left-text-fill' |
	'chat-left-quote' |
	'chat-left-quote-fill' |
	'chat-left-heart' |
	'chat-left-heart-fill' |
	'chat-left-fill' |
	'chat-left-dots' |
	'chat-left-dots-fill' |
	'chat-heart' |
	'chat-heart-fill' |
	'chat-fill' |
	'chat-dots' |
	'chat-dots-fill' |
	'cc-square' |
	'cc-square-fill' |
	'cc-circle' |
	'cc-circle-fill' |
	'cast' |
	'cassette' |
	'cassette-fill' |
	'cash' |
	'cash-stack' |
	'cash-coin' |
	'cart4' |
	'cart3' |
	'cart2' |
	'cart' |
	'cart-x' |
	'cart-x-fill' |
	'cart-plus' |
	'cart-plus-fill' |
	'cart-fill' |
	'cart-dash' |
	'cart-dash-fill' |
	'cart-check' |
	'cart-check-fill' |
	'caret-up' |
	'caret-up-square' |
	'caret-up-square-fill' |
	'caret-up-fill' |
	'caret-right' |
	'caret-right-square' |
	'caret-right-square-fill' |
	'caret-right-fill' |
	'caret-left' |
	'caret-left-square' |
	'caret-left-square-fill' |
	'caret-left-fill' |
	'caret-down' |
	'caret-down-square' |
	'caret-down-square-fill' |
	'caret-down-fill' |
	'card-text' |
	'card-list' |
	'card-image' |
	'card-heading' |
	'card-checklist' |
	'car-front' |
	'car-front-fill' |
	'capsule' |
	'capsule-pill' |
	'capslock' |
	'capslock-fill' |
	'camera2' |
	'camera' |
	'camera-video' |
	'camera-video-off' |
	'camera-video-off-fill' |
	'camera-video-fill' |
	'camera-reels' |
	'camera-reels-fill' |
	'camera-fill' |
	'calendar4' |
	'calendar4-week' |
	'calendar4-range' |
	'calendar4-event' |
	'calendar3' |
	'calendar3-week' |
	'calendar3-week-fill' |
	'calendar3-range' |
	'calendar3-range-fill' |
	'calendar3-fill' |
	'calendar3-event' |
	'calendar3-event-fill' |
	'calendar2' |
	'calendar2-x' |
	'calendar2-x-fill' |
	'calendar2-week' |
	'calendar2-week-fill' |
	'calendar2-range' |
	'calendar2-range-fill' |
	'calendar2-plus' |
	'calendar2-plus-fill' |
	'calendar2-month' |
	'calendar2-month-fill' |
	'calendar2-minus' |
	'calendar2-minus-fill' |
	'calendar2-heart' |
	'calendar2-heart-fill' |
	'calendar2-fill' |
	'calendar2-event' |
	'calendar2-event-fill' |
	'calendar2-day' |
	'calendar2-day-fill' |
	'calendar2-date' |
	'calendar2-date-fill' |
	'calendar2-check' |
	'calendar2-check-fill' |
	'calendar' |
	'calendar-x' |
	'calendar-x-fill' |
	'calendar-week' |
	'calendar-week-fill' |
	'calendar-range' |
	'calendar-range-fill' |
	'calendar-plus' |
	'calendar-plus-fill' |
	'calendar-month' |
	'calendar-month-fill' |
	'calendar-minus' |
	'calendar-minus-fill' |
	'calendar-heart' |
	'calendar-heart-fill' |
	'calendar-fill' |
	'calendar-event' |
	'calendar-event-fill' |
	'calendar-day' |
	'calendar-day-fill' |
	'calendar-date' |
	'calendar-date-fill' |
	'calendar-check' |
	'calendar-check-fill' |
	'calculator' |
	'calculator-fill' |
	'cake2' |
	'cake2-fill' |
	'cake' |
	'cake-fill' |
	'c-square' |
	'c-square-fill' |
	'c-circle' |
	'c-circle-fill' |
	'bus-front' |
	'bus-front-fill' |
	'bullseye' |
	'buildings' |
	'buildings-fill' |
	'building' |
	'building-x' |
	'building-up' |
	'building-slash' |
	'building-lock' |
	'building-gear' |
	'building-fill' |
	'building-fill-x' |
	'building-fill-up' |
	'building-fill-slash' |
	'building-fill-lock' |
	'building-fill-gear' |
	'building-fill-exclamation' |
	'building-fill-down' |
	'building-fill-dash' |
	'building-fill-check' |
	'building-fill-add' |
	'building-exclamation' |
	'building-down' |
	'building-dash' |
	'building-check' |
	'building-add' |
	'bug' |
	'bug-fill' |
	'bucket' |
	'bucket-fill' |
	'brush' |
	'brush-fill' |
	'browser-safari' |
	'browser-firefox' |
	'browser-edge' |
	'browser-chrome' |
	'broadcast' |
	'broadcast-pin' |
	'brilliance' |
	'brightness-low' |
	'brightness-low-fill' |
	'brightness-high' |
	'brightness-high-fill' |
	'brightness-alt-low' |
	'brightness-alt-low-fill' |
	'brightness-alt-high' |
	'brightness-alt-high-fill' |
	'briefcase' |
	'briefcase-fill' |
	'bricks' |
	'braces' |
	'braces-asterisk' |
	'boxes' |
	'box2' |
	'box2-heart' |
	'box2-heart-fill' |
	'box2-fill' |
	'box' |
	'box-seam' |
	'box-seam-fill' |
	'box-fill' |
	'box-arrow-up' |
	'box-arrow-up-right' |
	'box-arrow-up-left' |
	'box-arrow-right' |
	'box-arrow-left' |
	'box-arrow-in-up' |
	'box-arrow-in-up-right' |
	'box-arrow-in-up-left' |
	'box-arrow-in-right' |
	'box-arrow-in-left' |
	'box-arrow-in-down' |
	'box-arrow-in-down-right' |
	'box-arrow-in-down-left' |
	'box-arrow-down' |
	'box-arrow-down-right' |
	'box-arrow-down-left' |
	'bounding-box' |
	'bounding-box-circles' |
	'border' |
	'border-width' |
	'border-top' |
	'border-style' |
	'border-right' |
	'border-outer' |
	'border-middle' |
	'border-left' |
	'border-inner' |
	'border-center' |
	'border-bottom' |
	'border-all' |
	'bootstrap' |
	'bootstrap-reboot' |
	'bootstrap-fill' |
	'boombox' |
	'boombox-fill' |
	'bookshelf' |
	'bookmarks' |
	'bookmarks-fill' |
	'bookmark' |
	'bookmark-x' |
	'bookmark-x-fill' |
	'bookmark-star' |
	'bookmark-star-fill' |
	'bookmark-plus' |
	'bookmark-plus-fill' |
	'bookmark-heart' |
	'bookmark-heart-fill' |
	'bookmark-fill' |
	'bookmark-dash' |
	'bookmark-dash-fill' |
	'bookmark-check' |
	'bookmark-check-fill' |
	'book' |
	'book-half' |
	'book-fill' |
	'body-text' |
	'bluetooth' |
	'bluesky' |
	'blockquote-right' |
	'blockquote-left' |
	'binoculars' |
	'binoculars-fill' |
	'bing' |
	'bicycle' |
	'bezier2' |
	'bezier' |
	'bell' |
	'bell-slash' |
	'bell-slash-fill' |
	'bell-fill' |
	'behance' |
	'beaker' |
	'beaker-fill' |
	'battery' |
	'battery-low' |
	'battery-half' |
	'battery-full' |
	'battery-charging' |
	'basket3' |
	'basket3-fill' |
	'basket2' |
	'basket2-fill' |
	'basket' |
	'basket-fill' |
	'bar-chart' |
	'bar-chart-steps' |
	'bar-chart-line' |
	'bar-chart-line-fill' |
	'bar-chart-fill' |
	'bank2' |
	'bank' |
	'bandaid' |
	'bandaid-fill' |
	'ban' |
	'ban-fill' |
	'balloon' |
	'balloon-heart' |
	'balloon-heart-fill' |
	'balloon-fill' |
	'bag' |
	'bag-x' |
	'bag-x-fill' |
	'bag-plus' |
	'bag-plus-fill' |
	'bag-heart' |
	'bag-heart-fill' |
	'bag-fill' |
	'bag-dash' |
	'bag-dash-fill' |
	'bag-check' |
	'bag-check-fill' |
	'badge-wc' |
	'badge-wc-fill' |
	'badge-vr' |
	'badge-vr-fill' |
	'badge-vo' |
	'badge-vo-fill' |
	'badge-tm' |
	'badge-tm-fill' |
	'badge-sd' |
	'badge-sd-fill' |
	'badge-hd' |
	'badge-hd-fill' |
	'badge-cc' |
	'badge-cc-fill' |
	'badge-ar' |
	'badge-ar-fill' |
	'badge-ad' |
	'badge-ad-fill' |
	'badge-8k' |
	'badge-8k-fill' |
	'badge-4k' |
	'badge-4k-fill' |
	'badge-3d' |
	'badge-3d-fill' |
	'backspace' |
	'backspace-reverse' |
	'backspace-reverse-fill' |
	'backspace-fill' |
	'backpack4' |
	'backpack4-fill' |
	'backpack3' |
	'backpack3-fill' |
	'backpack2' |
	'backpack2-fill' |
	'backpack' |
	'backpack-fill' |
	'back' |
	'award' |
	'award-fill' |
	'at' |
	'asterisk' |
	'aspect-ratio' |
	'aspect-ratio-fill' |
	'arrows' |
	'arrows-vertical' |
	'arrows-move' |
	'arrows-fullscreen' |
	'arrows-expand' |
	'arrows-expand-vertical' |
	'arrows-collapse' |
	'arrows-collapse-vertical' |
	'arrows-angle-expand' |
	'arrows-angle-contract' |
	'arrow-up' |
	'arrow-up-square' |
	'arrow-up-square-fill' |
	'arrow-up-short' |
	'arrow-up-right' |
	'arrow-up-right-square' |
	'arrow-up-right-square-fill' |
	'arrow-up-right-circle' |
	'arrow-up-right-circle-fill' |
	'arrow-up-left' |
	'arrow-up-left-square' |
	'arrow-up-left-square-fill' |
	'arrow-up-left-circle' |
	'arrow-up-left-circle-fill' |
	'arrow-up-circle' |
	'arrow-up-circle-fill' |
	'arrow-through-heart' |
	'arrow-through-heart-fill' |
	'arrow-right' |
	'arrow-right-square' |
	'arrow-right-square-fill' |
	'arrow-right-short' |
	'arrow-right-circle' |
	'arrow-right-circle-fill' |
	'arrow-return-right' |
	'arrow-return-left' |
	'arrow-repeat' |
	'arrow-left' |
	'arrow-left-square' |
	'arrow-left-square-fill' |
	'arrow-left-short' |
	'arrow-left-right' |
	'arrow-left-circle' |
	'arrow-left-circle-fill' |
	'arrow-down' |
	'arrow-down-up' |
	'arrow-down-square' |
	'arrow-down-square-fill' |
	'arrow-down-short' |
	'arrow-down-right' |
	'arrow-down-right-square' |
	'arrow-down-right-square-fill' |
	'arrow-down-right-circle' |
	'arrow-down-right-circle-fill' |
	'arrow-down-left' |
	'arrow-down-left-square' |
	'arrow-down-left-square-fill' |
	'arrow-down-left-circle' |
	'arrow-down-left-circle-fill' |
	'arrow-down-circle' |
	'arrow-down-circle-fill' |
	'arrow-counterclockwise' |
	'arrow-clockwise' |
	'arrow-bar-up' |
	'arrow-bar-right' |
	'arrow-bar-left' |
	'arrow-bar-down' |
	'arrow-90deg-up' |
	'arrow-90deg-right' |
	'arrow-90deg-left' |
	'arrow-90deg-down' |
	'archive' |
	'archive-fill' |
	'apple' |
	'apple-music' |
	'app' |
	'app-indicator' |
	'anthropic' |
	'android2' |
	'android' |
	'amd' |
	'amazon' |
	'alt' |
	'alphabet' |
	'alphabet-uppercase' |
	'alipay' |
	'align-top' |
	'align-start' |
	'align-middle' |
	'align-end' |
	'align-center' |
	'align-bottom' |
	'alexa' |
	'alarm' |
	'alarm-fill' |
	'airplane' |
	'airplane-fill' |
	'airplane-engines' |
	'airplane-engines-fill' |
	'activity' |
	'9-square' |
	'9-square-fill' |
	'9-circle' |
	'9-circle-fill' |
	'8-square' |
	'8-square-fill' |
	'8-circle' |
	'8-circle-fill' |
	'7-square' |
	'7-square-fill' |
	'7-circle' |
	'7-circle-fill' |
	'6-square' |
	'6-square-fill' |
	'6-circle' |
	'6-circle-fill' |
	'5-square' |
	'5-square-fill' |
	'5-circle' |
	'5-circle-fill' |
	'4-square' |
	'4-square-fill' |
	'4-circle' |
	'4-circle-fill' |
	'3-square' |
	'3-square-fill' |
	'3-circle' |
	'3-circle-fill' |
	'2-square' |
	'2-square-fill' |
	'2-circle' |
	'2-circle-fill' |
	'123' |
	'1-square' |
	'1-square-fill' |
	'1-circle' |
	'1-circle-fill' |
	'0-square' |
	'0-square-fill' |
	'0-circle' |
	'0-circle-fill';
